### PR TITLE
Fix template type issue

### PR DESCRIPTION
**Pull request by jlack1987**
### Changelog
Fix a compiler error involving template types.

### Docs

None

### Description

When trying to compile on Ubuntu 24.04 I get the following compiler error
```bash
foxglove-sdk/cpp/foxglove/include/foxglove/server/parameter.hpp:335:50: error: expected unqualified-id before ‘.’ token
  335 |       result.emplace(dictKey, dictValue.template .get<T>());
      |                                                  ^
foxglove-sdk/cpp/foxglove/include/foxglove/server/parameter.hpp:335:56: error: expected primary-expression before ‘>’ token
  335 |       result.emplace(dictKey, dictValue.template .get<T>());
      |                                                        ^
foxglove-sdk/cpp/foxglove/include/foxglove/server/parameter.hpp:335:58: error: expected primary-expression before ‘)’ token
  335 |       result.emplace(dictKey, dictValue.template .get<T>());
```

### CODE REVIEW

**Comment by jlack1987** [comment]
Just found that there was another [issue](https://github.com/foxglove/foxglove-sdk/issues/514) reported for this bug
