### ISSUE TITLE
foxglove bridge not working on ubuntu 22.01

### ISSUE THREAD

**Issue by jeaninevbrr** [foxglove/foxglove-sdk#638]
**Description**
The foxglove bridge package does not build on ubuntu 22. It has something to do with glibc version available in ubuntu and needed by the component. This is my error log:
```
docker run --rm -v /home/jeanine/dev/foxglove-sdk/ros/..:/sdk foxglove-sdk-ros-humble make USE_LOCAL_SDK=OFF build
colcon build --cmake-args -DUSE_LOCAL_SDK=OFF
Starting >>> foxglove_bridge
Starting >>> foxglove_msgs
Finished <<< foxglove_msgs [18.7s]
--- stderr: foxglove_msgs
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_LOCAL_SDK


---
--- stderr: foxglove_bridge
/usr/bin/ld: libfoxglove_bridge_component.so: undefined reference to `__isoc23_strtol'
/usr/bin/ld: libfoxglove_bridge_component.so: undefined reference to `__isoc23_sscanf'
collect2: error: ld returned 1 exit status
gmake[3]: *** [CMakeFiles/foxglove_bridge.dir/build.make:172: foxglove_bridge] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:216: CMakeFiles/foxglove_bridge.dir/all] Error 2
gmake[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: libfoxglove_bridge_component.so: undefined reference to `__isoc23_strtol'
/usr/bin/ld: libfoxglove_bridge_component.so: undefined reference to `__isoc23_sscanf'
collect2: error: ld returned 1 exit status
gmake[3]: *** [CMakeFiles/smoke_test.dir/build.make:192: smoke_test] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:245: CMakeFiles/smoke_test.dir/all] Error 2
gmake[1]: *** [Makefile:146: all] Error 2
---
Failed   <<< foxglove_bridge [57.9s, exited with code 2]
[Processing: foxglove_bridge]

Summary: 1 package finished [58.0s]
  1 package failed: foxglove_bridge
  2 packages had stderr output: foxglove_bridge foxglove_msgs
make: *** [Makefile:25: build] Error 2
make: *** [Makefile:53: docker-build-humble] Error 2
```

- Version: 0.14 (0.13 works!)
- Platform: Ubuntu 22.04

**Steps To Reproduce**
Run either 
```
cd ros
make
```
or 
```
cd ros
make docker-build-humble
```

**Expected Behavior**
That the package builds :)

**Comment by ericmlujan** [comment]
@jeaninevbrr thanks for the bug report! I'll be looking into this and seeing what we can do to fix the build. My initial hypothesis is that with recent changes that went into our Rust SDK to support WebSocket Secure connections in the bridge, coupled with our prebuilt library artifacts being built on Ubuntu 24.04, we're now relying on symbols from a libc version that's newer than what's available in Ubuntu 22.04. But why exactly that's happening and the ultimate resolution is something I still need to look into.

In the meantime, if you're blocked on this, you can try building the SDK binaries in a local docker container and linking against them as a temporary workaround. This seemed to work for me.

From repo root:
```
make build-cpp
```

then from `ros/`:
```
make USE_LOCAL_SDK=ON docker-build-humble
```
